name: Creating a Keyboard Oriented Puzzle Game for Flutter

type: flutter

steps:
  - name: Step 1
    directory: step_01
    has_solution: true
  - name: Step 2
    directory: step_02
    has_solution: false
  - name: Step 3
    directory: step_03
    has_solution: true